# Dependencies
markdown:         maruku
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            denosawr
tagline:          'something'
description:      'a blog where I ramble about all sorts of things.'
url:              https://denosawr.github.io/blog
baseurl:          /blog

author:
  name:           'deno'
  url:            https://github.com/denosawr

paginate:         5

# Custom vars
version:          1

github:
  repo:           https://github.com/denosawr/denosawr.github.io
