# Dependencies
markdown:         maruku
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            french
tagline:          'study notes'
description:      'my learnings and test revision for my journey through the French language.'
url:              https://denosawr.github.io/french-notes
baseurl:          /french-notes

author:
  name:           'deno'
  url:            https://github.com/denosawr

paginate:         5

# Custom vars
version:          1

github:
  repo:           https://github.com/denosawr/french-learning
